name: 'Integrate'
on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: 'CI'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: false
      - name: 'Setup the Rust toolchain'
        run: |
          rustup override set ${{ matrix.toolchain }}
          rustup --version
          rustc --version
          cargo --version
      - name: 'Build the library'
        run: cargo build
      - name: 'Run tests for the library'
        run: cargo test
